baseURL                  = "https://example.com/"           # Your domain name. Must end with "/"
languageCode             = "de-De"
defaultContentLanguage   = "de"
#isMultilingual           = false
title                    = "DVZeiten"
theme                    = "tale"

[params]
  author = "Gärtner Müller"

[Author]
  name = ".YA"